---
- name: Deploy WAR file to on-premises server
  hosts: Target
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: /var/lib/jenkins/workspace/CI_CD_PIPELINE/target/petclinic.war
        dest: /target/petclinic.war
       

   
